CREATE DATABASE pizza_db;
USE pizza_db;

CREATE TABLE CUSTOMER
(
  CUSTOMER_ID   INT          NOT NULL AUTO_INCREMENT,
  FIRST_NAME    VARCHAR(100) NULL,
  LAST_NAME     VARCHAR(100) NULL,
  BIRTH_DATE    DATE         NULL,
  ADDRESS       VARCHAR(100) NULL,
  PHONE_NUMBER  VARCHAR(20)  NULL,
  PIZZA_COUNT   INT          NULL,
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE DELIVERY_PERSON
(
  DELIVERY_PERSON_ID INT          NOT NULL AUTO_INCREMENT,
  FIRST_NAME         VARCHAR(100) NULL,
  LAST_NAME          VARCHAR(100) NULL,
  IS_AVAILABLE       BOOLEAN      NULL,
  PRIMARY KEY (DELIVERY_PERSON_ID)
);

CREATE TABLE DISCOUNT_CODE
(
  DISCOUNT_CODE_ID INT          NOT NULL AUTO_INCREMENT,
  CODE             VARCHAR(30)  NOT NULL,
  DISCOUNT_PERCENT DECIMAL(5,2) NOT NULL,
  IS_USED          BOOLEAN      NULL,
  PRIMARY KEY (DISCOUNT_CODE_ID)
);

CREATE TABLE STATUS
(
  STATUS_ID   INT          NOT NULL AUTO_INCREMENT,
  STATUS_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (STATUS_ID)
);

CREATE TABLE PRODUCT_TYPE
(
  PRODUCT_TYPE_ID   INT          NOT NULL AUTO_INCREMENT,
  PRODUCT_TYPE_NAME VARCHAR(100) NOT NULL,
  MARGIN            INT          NULL,
  VAT               INT          NULL,
  PRIMARY KEY (PRODUCT_TYPE_ID)
);

CREATE TABLE PRODUCT
(
  PRODUCT_ID      INT          NOT NULL AUTO_INCREMENT,
  PRODUCT_NAME    VARCHAR(100) NOT NULL,
  IS_VEGAN        BOOLEAN      NULL,
  IS_VEGETARIAN   BOOLEAN      NULL,
  COST            DECIMAL(6,2) NULL,
  PRODUCT_TYPE_ID INT          NOT NULL,
  PRIMARY KEY (PRODUCT_ID),
  FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (PRODUCT_TYPE_ID)
);

CREATE TABLE INGREDIENT
(
  INGREDIENT_ID      INT          NOT NULL AUTO_INCREMENT,
  INGREDIENT_NAME    VARCHAR(100) NULL,
  COST               DECIMAL(6,2) NULL,
  IS_VEGAN_SAFE      BOOLEAN      NULL,
  IS_VEGETARIAN_SAFE BOOLEAN      NULL,
  IS_ALCOHOL         BOOLEAN      NULL,
  PRIMARY KEY (INGREDIENT_ID)
);



CREATE TABLE ORDERS
(
  ORDER_ID           INT          NOT NULL AUTO_INCREMENT,
  CREATED_AT         DATETIME     NULL,
  DELIVERED_AT       DATETIME     NULL,
  TOTAL_PRICE        DECIMAL(8,2) NULL,
  DISCOUNT_CODE_ID   INT          NULL,
  DELIVERY_PERSON_ID INT          NOT NULL,
  STATUS_ID          INT          NOT NULL,
  CUSTOMER_ID        INT          NOT NULL,
  PRIMARY KEY (ORDER_ID),
  FOREIGN KEY (DISCOUNT_CODE_ID) REFERENCES DISCOUNT_CODE (DISCOUNT_CODE_ID),
  FOREIGN KEY (DELIVERY_PERSON_ID) REFERENCES DELIVERY_PERSON (DELIVERY_PERSON_ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE ORDER_ITEM
(
  ORDER_ITEM_ID INT NOT NULL AUTO_INCREMENT,
  AMOUNT        INT NOT NULL,
  PRODUCT_ID    INT NOT NULL,
  ORDER_ID      INT NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);



CREATE TABLE PRODUCT_INGREDIENT
(
  INGREDIENT_ID         INT NOT NULL,
  PRODUCT_ID            INT NOT NULL,
  NUMBER_OF_INGREDIENTS INT NULL,
  PRIMARY KEY (INGREDIENT_ID, PRODUCT_ID),
  FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);



